name: build

on:
  pull_request:
  push:
    branches:
      - master
  schedule:
    # Prime the caches every Monday
    - cron: 0 1 * * MON

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
        ocaml-compiler:
          - "4.08"
          - "4.09"
          - "4.10"
          - "4.11"
          - "4.12"
          - "4.13"
          - "4.14"
          - "5.0"
          - "5.1"
          - "5.2"

    runs-on: ${{ matrix.os }}

    steps:
      - name: Set git to use LF
        if: matrix.ocaml-compiler < 5.2
        run: |
          git config --global core.autocrlf false
          git config --global core.eol lf
          git config --global core.ignorecase false

      - name: Checkout tree
        uses: actions/checkout@v4

      - name: Set-up OCaml ${{ matrix.ocaml-compiler }}
        if: runner.os == 'Windows'
        uses: ocaml/setup-ocaml@v2
        with:
          ocaml-compiler: ${{ matrix.ocaml-compiler }}
          opam-repositories: |
            dra27: https://github.com/dra27/opam-repository.git#windows-5.0
            default: https://github.com/ocaml-opam/opam-repository-mingw.git#sunset
            opam: https://github.com/ocaml/opam-repository.git
          dune-cache: true
          opam-depext: ${{ !matrix.skip-test }}
          opam-depext-flags: --with-test

      - name: Set-up OCaml ${{ matrix.ocaml-compiler }}
        if: runner.os != 'Windows'
        uses: ocaml/setup-ocaml@v2
        with:
          ocaml-compiler: ${{ matrix.ocaml-compiler }}
          allow-prerelease-opam: true
          dune-cache: true
          opam-depext: ${{ !matrix.skip-test }}
          opam-depext-flags: --with-test

      - run: opam install . --with-test --deps-only

      - run: opam exec -- make test

      - run: OCAMLBUILD=$(pwd)/ocamlbuild.native opam exec -- make -C bootstrap

      - run: opam exec -- make distclean
      - run: opam exec -- opam pin add -n -k path ocamlbuild .
      - run: opam exec -- opam install -v ocamlbuild
      - run: opam exec -- opam install -v mtime.1.0.0 # this tests topkg, with stub libraries
      - run: opam exec -- opam install -v inotify.2.3 # this tests oasis, with stub libraries
        if: matrix.ocaml-compiler < 5
      - run: opam exec -- opam install -v cpuid.0.1.1 # this tests the ocb-stubblr plugin
      - run: opam exec -- opam install -v shcaml.0.2.1 # this tests the cppo plugin
        if: matrix.ocaml-compiler < 5
